import Navbar from "./components/navbar";
import globals from "./globals.css"


export const metadata = {
  title: "Cantor College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <header>
            <Navbar />
          </header>

          <main>
            {children}
          </main>


          <footer>
            <li>How to find us:</li>
            <li>Cantor College</li>
            <li>Main Street</li>
            <li>Sheffield</li>
            <li>SC4 2BB</li>
            <li>Tel:(01321) 2340 235</li>
            <li>Fax: (01321) 2340 236</li>
            <li>Email: info@cantorcollege.ac.uk</li>
          </footer>
        </div>
      </body>
    </html>
  );
}
